Support printing sensors using `ign model`
ignitionrobotics/ign-gazebo pull request #1157
Opened 2021-11-01 23:57 UTC by nkoenig

Signed-off-by: Nate Koenig <nate@openrobotics.org>

# 🎉 New feature

## Summary

Print some sensor information using `ign model`. Output is currently limited to altimeter, imu, camera, and rgbd cameras.

## Test it

1. `ign gazebo -v4 sensors.sdf`
2. `ign model -m sensors_box`

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Updated documentation (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-11-02 09:19 UTC, ahcorde requested changes

2021-11-02 09:19 UTC, ahcorde commented on src/cmd/ModelCommandAPI.cc
> +/// \param[in] _camera The camera to output
```suggestion
/// \param[in] _camera The camera to output
/// \param[in] _spaces Number of spaces to indent for every line
```

2021-11-02 09:19 UTC, ahcorde commented on src/cmd/ModelCommandAPI.cc
> +/// \brief Print info about a camera sensor.
```suggestion
/// \brief Print info about a RGBD camera sensor.
```

2021-11-02 14:48 UTC, nkoenig commented on src/cmd/ModelCommandAPI.cc
> +/// \brief Print info about a camera sensor.
07abdbf

2021-11-02 14:48 UTC, nkoenig commented on src/cmd/ModelCommandAPI.cc
> +/// \param[in] _camera The camera to output
07abdbf

2021-11-03 08:59 UTC, ahcorde requested changes

2021-11-03 08:59 UTC, ahcorde commented on src/ModelCommandAPI_TEST.cc
> +  serverConfig.SetSdfFile(std::string(PROJECT_SOURCE_PATH) +
ignition::common::JointPaths

2021-11-03 08:59 UTC, ahcorde commented on src/ModelCommandAPI_TEST.cc
> +  serverConfig.SetSdfFile(std::string(PROJECT_SOURCE_PATH) +
ignition::common::JointPaths

2021-11-03 08:59 UTC, ahcorde commented on src/ModelCommandAPI_TEST.cc
> +  serverConfig.SetSdfFile(std::string(PROJECT_SOURCE_PATH) +
ignition::common::JointPaths

2021-11-04 15:50 UTC, nkoenig commented on src/ModelCommandAPI_TEST.cc
> +  serverConfig.SetSdfFile(std::string(PROJECT_SOURCE_PATH) +
eae7bcd

2021-11-04 15:50 UTC, nkoenig commented on src/ModelCommandAPI_TEST.cc
> +  serverConfig.SetSdfFile(std::string(PROJECT_SOURCE_PATH) +
eae7bcd

2021-11-04 16:57 UTC, nkoenig commented on src/ModelCommandAPI_TEST.cc
> +  serverConfig.SetSdfFile(std::string(PROJECT_SOURCE_PATH) +
eae7bcd

2021-11-04 17:06 UTC, ahcorde requested changes
Same in the other JoinPaths

2021-11-04 17:06 UTC, ahcorde commented on src/ModelCommandAPI_TEST.cc
> +                          "/test/worlds/static_diff_drive_vehicle.sdf"));
```suggestion
      ignition::common::joinPaths(std::string(PROJECT_SOURCE_PATH), "test", "worlds", "static_diff_drive_vehicle.sdf"));
```

2021-11-04 17:46 UTC, nkoenig commented on src/ModelCommandAPI_TEST.cc
> +                          "/test/worlds/static_diff_drive_vehicle.sdf"));
Right, thanks. Done.

2021-11-04 17:46 UTC, ahcorde requested changes

2021-11-04 17:46 UTC, ahcorde commented on src/ModelCommandAPI_TEST.cc
> +        "/test/worlds/static_diff_drive_vehicle.sdf"));
still need to split this with comas:
```
"test", "worlds", "static_diff_drive_vehicle.sdf"));
```

2021-11-04 17:47 UTC, nkoenig commented on src/ModelCommandAPI_TEST.cc
> +        "/test/worlds/static_diff_drive_vehicle.sdf"));
Yup, thanks. Done.

2021-11-04 17:47 UTC, ahcorde approved these changes

2021-11-05 03:58 UTC, merged