Added altimeter sensor inspector
ignitionrobotics/ign-gazebo pull request #1172
Opened 2021-11-06 01:11 UTC by nkoenig

Signed-off-by: Nate Koenig <nate@openrobotics.org>

# 🎉 New feature

## Summary

Builds on #1171 by adding a GUI inspector for altimeters.

This PR also demonstrates how to add a new component inspector element. 

## Test it

1. `ign gazebo -v 4 sensors.sdf`
2. Take note of the output from `ign model -m sensors_box -l link -s altimeter`
3. Select the altimeter sensor in the entity tree.
4. Make some changes to the values in the component inspector. 
5. Rerun `ign model -m sensors_box -l link -s altimeter` and you should see the changes.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-11-08 20:27 UTC, ahcorde requested changes

2021-11-08 20:27 UTC, ahcorde commented on src/gui/plugins/component_inspector/Altimeter.cc
> +#include "ComponentInspector.hh"
alphabetize

2021-11-11 00:12 UTC, nkoenig commented on src/gui/plugins/component_inspector/Altimeter.cc
> +#include "ComponentInspector.hh"
Fixed in a4f8336

2021-11-18 01:48 UTC, iche033 approved these changes
looks good to me.

2021-11-18 15:53 UTC, merged