Added magnetometer inspector
ignitionrobotics/ign-gazebo pull request #1173
Opened 2021-11-06 01:15 UTC by nkoenig

Signed-off-by: Nate Koenig <nate@openrobotics.org>

# 🎉 New feature

## Summary

Builds on #1171 by adding a GUI inspector for altimeters.

This PR also demonstrates how to add a new component inspector element. 

## Test it

1. `ign gazebo -v 4 sensors.sdf`
2. Take note of the output from `ign model -m sensors_box -l link -s magnetometer`
3. Select the magnetometer sensor in the entity tree.
4. Make some changes to the values in the component inspector. 
5. Rerun `ign model -m sensors_box -l link -s magnetometer` and you should see the changes.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-11-08 20:28 UTC, ahcorde requested changes

2021-11-08 20:28 UTC, ahcorde commented on src/gui/plugins/component_inspector/Magnetometer.cc
> +#include "Types.hh"
alphabetize

2021-11-11 00:17 UTC, nkoenig commented on src/gui/plugins/component_inspector/Magnetometer.cc
> +#include "Types.hh"
Fixed in cd8bb01

2021-11-18 22:43 UTC, mjcarroll approved these changes
Once I added `use_event` to `WorldControl` in `~/.ignition/gazebo/6/gui.config`, it was good to go:

```
<!-- World control -->
<plugin filename="WorldControl" name="World control">
  <ignition-gui>
    <title>World control</title>
    <property type="bool" key="showTitleBar">false</property>
    <property type="bool" key="resizable">false</property>
    <property type="double" key="height">72</property>
    <property type="double" key="width">121</property>
    <property type="double" key="z">1</property>

    <property type="string" key="state">floating</property>
    <anchors target="3D View">
      <line own="left" target="left"/>
      <line own="bottom" target="bottom"/>
    </anchors>
  </ignition-gui>

  <play_pause>true</play_pause>
  <step>true</step>
  <start_paused>true</start_paused>
  <use_event>true</use_event>

</plugin>
```

2021-11-19 00:33 UTC, merged