Update SdfGenerator to save joint data to file
ignitionrobotics/ign-gazebo pull request #1220
Opened 2021-11-20 04:41 UTC by iche033

# 🎉 New feature

depends on:
* #1209 
* https://github.com/ignitionrobotics/sdformat/pull/759

## Summary

similar to #1209, this PR extends SdfGenerator to pull joint data from ECM and save them to SDF file.

Note that the `components::Joint` component does not store a `sdf::Joint` DOM object. Various joint properties are stored in different Joint* components, and currently ign-gazebo does not have components for all joint properties. So as the result, not all joint properties can be saved to sdf file.

## Test it

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# ➡️ Forward port

Port <FROM_BRANCH> to <TO_BRANCH>

Branch comparison: https://github.com/ignitionrobotics/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# 🎈 Release

Preparation for <X.Y.Z> release.

Comparison to <x.y.z>: https://github.com/ignitionrobotics/<REPO>/compare/<LATEST_TAG_BRANCH>...<RELEASE_BRANCH>

Needed by <PR(s)>

## Checklist
- [ ] Asked team if this is a good time for a release
- [ ] There are no changes to be ported from the previous major version
- [ ] No PRs targeted at this major version are close to getting in
- [ ] Bumped minor for new features, patch for bug fixes
- [ ] Updated changelog
- [ ] Updated migration guide (as needed)
- [ ] Link to PR updating dependency versions in appropriate repository in [ignition-release](https://github.com/ignition-release) (as needed): <LINK>

**Note to maintainers**: Remember to use **Squash-Merge**

2021-11-22 08:24 UTC, ahcorde requested changes

2021-11-22 08:24 UTC, ahcorde commented on test/integration/save_world.cc
> +  this->LoadWorld("test/worlds/joint_sensor.sdf");
ignition::common::JoinPaths

```suggestion
  this->LoadWorld("test/worlds/joint_sensor.sdf");
```

2021-11-29 21:47 UTC, iche033 commented on test/integration/save_world.cc
> +  this->LoadWorld("test/worlds/joint_sensor.sdf");
done. ceafa41

2021-11-30 17:15 UTC, nkoenig approved these changes

2021-11-30 17:24 UTC, nkoenig commented
I'm going to merge this done in order to speed up and consolidate the CI tests.

2021-11-30 17:24 UTC, merged