Add gazebo Entity id to rendering sensor's user data
ignitionrobotics/ign-gazebo pull request #1381
Opened 2022-03-10 02:37 UTC by iche033

Signed-off-by: Ian Chen <ichen@osrfoundation.org>

# 🎉 New feature

## Summary

Adds the `gazebo::Entity` id to a `rendering::Sensor`'s UserData object. The main use case is so that we can get back the corresponding gazebo `Entity` in the rendering thread when processing sensors.

## Test it
Run the `INTEGRATION_sensors_system` test.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-03-10 08:49 UTC, ahcorde requested changes
alphabetize headers

2022-03-10 08:49 UTC, ahcorde commented on test/integration/sensors_system.cc
> +#include <unordered_set>
alphabetize

2022-03-10 18:40 UTC, iche033 commented on test/integration/sensors_system.cc
> +#include <unordered_set>
83432faec87bc75511089be690821f49970deae8

2022-03-14 15:36 UTC, nkoenig approved these changes

2022-03-15 11:29 UTC, ahcorde approved these changes

2022-03-15 15:57 UTC, merged

2022-04-13 21:29 UTC, osrf-triage commented
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-04-13-fortress-edifice/1367/1