Fix nested model topic name in JointStatePublisher
ignitionrobotics/ign-gazebo pull request #1405
Opened 2022-03-22 21:48 UTC by iche033

Signed-off-by: Ian Chen <ichen@osrfoundation.org>

# 🦟 Bug fix

## Summary

The joint-state-publisher system currently assumes it's always attached to the top level model and hence generates an incorrect topic name for nested models. This PR updates it to generate the correct topic name.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-03-23 05:13 UTC, chapulina approved these changes

2022-03-23 08:35 UTC, ahcorde requested changes

2022-03-23 08:35 UTC, ahcorde commented on test/integration/joint_state_publisher_system.cc
> +      "/test/worlds/diff_drive_nested.sdf");
`ignition::common::joinPaths`

2022-03-23 08:35 UTC, ahcorde commented on test/integration/joint_state_publisher_system.cc
> +      std::cerr << "asdfasdf" << std::endl;
remove

2022-03-23 17:26 UTC, iche033 commented on test/integration/joint_state_publisher_system.cc
> +      std::cerr << "asdfasdf" << std::endl;
oops, removed. [8f540bf](https://github.com/ignitionrobotics/ign-gazebo/pull/1405/commits/8f540bfdd73a472665b3e2c08a96ece1a43880c0)

2022-03-23 17:26 UTC, iche033 commented on test/integration/joint_state_publisher_system.cc
> +      "/test/worlds/diff_drive_nested.sdf");
done. [8f540bf](https://github.com/ignitionrobotics/ign-gazebo/pull/1405/commits/8f540bfdd73a472665b3e2c08a96ece1a43880c0)

2022-03-24 00:48 UTC, merged

2022-04-13 21:29 UTC, osrf-triage commented
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-04-13-fortress-edifice/1367/1