Visualize Lidar Plugin for ign-gazebo
ignitionrobotics/ign-gazebo pull request #301
Opened 2020-08-20 13:17 UTC by mihirk284

2020-08-20 13:26 UTC, ahcorde requested changes

2020-08-20 13:26 UTC, ahcorde commented on src/gui/plugins/visualize_lidar/VisualizeLidar.hh
> +    /// \brief Notify that topic name has changed
review the documentation here and below

2020-08-20 13:26 UTC, ahcorde commented on examples/worlds/visualize_lidar.sdf
> +
remove white line

2020-08-20 13:26 UTC, ahcorde commented on examples/worlds/visualize_lidar.sdf
> +
remove white line

2020-08-20 13:26 UTC, ahcorde commented on examples/worlds/visualize_lidar.sdf
> +      </uri>
```suggestion
      <uri>https://fuel.ignitionrobotics.org/1.0/openrobotics/models/Playground</uri>
```

2020-08-20 22:11 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +#include <ignition/common/VideoEncoder.hh>
most of these headers are not needed. Can you remove the ones not used?

2020-08-20 22:11 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +    public: double maxVisualRange;
initialize the min max range variables to 0.0

2020-08-20 22:13 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +  switch (_type) {
nit: bracket on new line

2020-08-20 22:14 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +            break;
`this->dataPtr->visualType =` on new line with two space indentation

2020-08-20 22:21 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +          this->MaxRangeChanged();
`break` here?

2020-08-20 22:24 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +        if (success == true)
`if (success)`

2020-08-20 22:25 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +          if (foundChild == false)
`if (!foundChild)`

2020-08-20 22:25 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +        for (auto i = 0ul; i < lidarURIVec.size()-1; i++)
`auto i = 0ul` -> `size_t i = 0u`

2020-08-20 22:28 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +              if (i+1 == lidarURIVec.size()-1)
I think the logic in this block assumes the model > link > sensor hierarchy? 

We also support nested models, i.e.g model > model > link > sensor, in which case the logic above may not work?

2020-08-20 22:31 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +    ignwarn << "Failed to create lidar, lidar visual plugin won't work."
`lidar visual plugin` -> `visualize lidar plugin`?

2020-08-20 22:42 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +  this->dataPtr->lidar = scene->CreateLidarVisual();
I don't see the visual destroyed? we need to be careful not to leave any dangling visuals around when the plugin exits

2020-08-24 21:00 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +    this->dataPtr->lidar->SetType(rendering::LidarVisualType::LVT_NONE);
you should be able to call `this->dataPtr->lidar->SetVisible(false)` to make it invisible, which is a faster operation than clearing all the lidar data. Same for re-enabling the lidar visual display below

2020-08-24 21:05 UTC, iche033 commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +  this->dataPtr->lidar = scene->CreateLidarVisual();
following up on this, we should destroy the visual when the user closes the plugin, i.e.  by clicking on `X` in the corner of the plugin window. Currently I see that lidar visual remains in the scene after exiting the plugin, and when I open the same plugin again, a duplicate lidar visual gets created.

2020-08-25 20:23 UTC, iche033 commented
one small issue: 
1.  uncheck `Display Lidar Visual` -> lidar becomes invisible - correct
1. uncheck `Show Non Hitting Rays` -> lidar becomes visible again when it should stay invisible

2020-08-26 07:56 UTC, mihirk284 commented
> one small issue:
> 
> 1. uncheck `Display Lidar Visual` -> lidar becomes invisible - correct
> 2. uncheck `Show Non Hitting Rays` -> lidar becomes visible again when it should stay invisible

@iche033  Thanks for bringing it to my attention. I think this is happening whenever the `DynamicRenderables` inside the visual are being deleted and new renderables are being used to display the visual. This happens in the case when there is a change in the `LidarVisualType` or if we have `displayNonHitting = false`.
This is happening despite having `lidar->SetVisible(false)`. The new `DynamicRenderables` generated after this operation always cause the visual to show up.

I can solve this by not updating the visual in the plugin if the display option is off.
Or should we change something in the rendering part of the code?

2020-08-26 22:57 UTC, iche033 commented
> Or should we change something in the rendering part of the code?
sounds like once we clear the visual data and create new ones in ign-rendering, we need to call `SetVisible` again with the current visible value so that the visibility is correct.

2020-08-31 21:12 UTC, iche033 commented
> sounds like once we clear the visual data and create new ones in ign-rendering, we need to call SetVisible again with the current visible value so that the visibility is correct.

fixed in ignitionrobotics/ign-rendering#133

2020-08-31 21:14 UTC, iche033 commented
changes look good. Can you merge with / rebase on `master`?

2020-09-03 03:39 UTC, iche033 approved these changes

2020-09-04 07:03 UTC, ahcorde approved these changes
LGTM, two small comments

2020-09-04 07:03 UTC, ahcorde commented on src/gui/plugins/visualize_lidar/VisualizeLidar.cc
> +    return;
you can remove this line, right?

2020-09-06 01:49 UTC, chapulina reviewed
The Mac build failed, I think we need to bump the `ign-rendering` revision on `homebrew-simulation`:

```
/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/ign-gazebo/src/gui/plugins/visualize_lidar/VisualizeLidar.cc:49:10: fatal error: 'ignition/rendering/LidarVisual.hh' file not found
#include "ignition/rendering/LidarVisual.hh"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2020-09-10 16:56 UTC, chapulina commented
@osrf-jenkins run tests, let's see what happens now

2020-09-21 23:36 UTC, chapulina commented
@osrf-jenkins run tests :crossed_fingers:

2020-09-23 01:10 UTC, merged