Update the cmd out for custom render engines
ignitionrobotics/ign-gazebo pull request #373
Opened 2020-09-24 19:59 UTC by JShep1

See https://github.com/ignitionrobotics/ign-rendering/pull/142 for the PR adding this functionality.

Signed-off-by: John Shepherd <john@openrobotics.org>

2020-10-13 07:05 UTC, iche033 approved these changes

2020-10-14 19:17 UTC, chapulina requested changes
Works for me! I tested with `ign-rendering`'s hello world example like this:

```
cd src/ign-rendering/examples/hello_world_plugin/build
IGN_GAZEBO_RENDER_ENGINE_PATH=`pwd` ign gazebo -v 2 sensors_demo.sdf --render-engine HelloWorldPlugin
```



Mind adding a tutorial similar to https://github.com/ignitionrobotics/ign-gazebo/blob/main/tutorials/physics.md?

I think you can get most of the way there by copying that tutorial and `s/physics/rendering`

2020-10-14 19:20 UTC, chapulina commented
Removed the "needs upstream release" label because `ign-rendering 3.2.0` was released. 

Mind updating the minimum required version here?

https://github.com/ignitionrobotics/ign-gazebo/blob/0d16dc96ec0544440a082f37d2cfa72a97dcbc9f/CMakeLists.txt#L117

2020-10-20 17:15 UTC, JShep1 commented on src/rendering/RenderUtil.cc
> +  public: std::string pluginPathEnv = "IGN_GAZEBO_RENDER_ENGINE_PATH";
2e0e9f1eea6c9da542af501e3b95d55fa3bd1f37

2020-10-20 17:18 UTC, JShep1 commented
> Mind adding a tutorial similar to https://github.com/ignitionrobotics/ign-gazebo/blob/main/tutorials/physics.md?

Yep! Tutorial is [here](https://github.com/ignitionrobotics/ign-rendering/blob/ign-rendering3/tutorials/03_rendering_plugins.md) and an example is [here](https://github.com/ignitionrobotics/ign-rendering/tree/ign-rendering3/examples/hello_world_plugin)

2020-10-27 00:38 UTC, chapulina approved these changes

2020-10-27 00:38 UTC, merged