Bazel updates for gazebo4
ignitionrobotics/ign-gazebo pull request #475
Opened 2020-12-06 04:18 UTC by JShep1

Signed-off-by: John Shepherd <john@openrobotics.org>

2021-02-25 19:23 UTC, mahiuchun commented
I see a link error due to `copyElement` being defined in both `ign_gazebo/src/ServerConfig.cc` and `ign_launch/plugins/gazebo_server/GazeboServer.cc`. Please use `static` or put them into anonymous namespace if they are meant to be local helper functions.

2021-03-08 19:10 UTC, mahiuchun commented on src/ign.cc
> +  Q_INIT_RESOURCE(gazebo);
I had to remove this in order to avoid a dynamic link error.

2021-05-03 03:48 UTC, mahiuchun requested changes
It appears that this PR has not caught up with https://github.com/ignitionrobotics/ign-msgs/commit/e2709830f295061629eee65b2dcd876e80662556 yet so it does not build right now.

2021-08-17 00:55 UTC, chapulina requested changes
The build is broken

2021-11-10 17:40 UTC, chapulina commented
@mjcarroll , I'll close this as it seems outdated

2021-11-10 17:40 UTC, closed without merging