Allow to create light with the create service
ignitionrobotics/ign-gazebo pull request #513
Opened 2020-12-23 13:22 UTC by ahcorde

This PR will allow to create lights with the service `world/<world_name>/create` 

I'm writting a tutorial to control lights (create, modify and delete).

Signed-off-by: ahcorde <ahcorde@gmail.com>

2020-12-23 13:26 UTC, ahcorde commented
By the way, I know there are some `Convert` funtions on `ign-msgs` but it does not depend on `sdformat`. The conversion that I need is between `ignition::msgs::Light` and `sdf::Light`. where is the right place to locate this funtion ? Some can idea can be applied to `Set`.

2020-12-23 18:43 UTC, iche033 commented
> By the way, I know there are some `Convert` funtions on `ign-msgs` but it does not depend on `sdformat`. The conversion that I need is between `ignition::msgs::Light` and `sdf::Light`. where is the right place to locate this funtion ? Some can idea can be applied to `Set`.

Is this what you are looking for?
https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/src/Conversions.cc#L444

2020-12-23 20:44 UTC, ahcorde commented
> Is this what you are looking for?
> https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/src/Conversions.cc#L444

yes, https://github.com/ignitionrobotics/ign-gazebo/pull/513/commits/a677a912a51952580133401c4c21d4b0e8594201

2020-12-28 23:46 UTC, chapulina requested changes

2020-12-28 23:46 UTC, chapulina commented on src/systems/user_commands/UserCommands.cc
> +      sdf::Light lightSDF = convert<sdf::Light>(lightMsg);
How about just populating `root` with `lightSDF` and letting the rest of this function handle things like naming and pose? You'll probably need to set `isLight` to true. This way there's less duplication and fields like `allow_renaming` are also used.

2021-01-07 22:04 UTC, iche033 commented on src/systems/user_commands/UserCommands.cc
> +        std::to_string(sdfLight.RawPose().Rot().Yaw()) +
nothing to change here but just a note that many ign math classes have the `<<` operator so if you use `std::stringstream`, you can just do `ss << sdfLight.RawPose()`

2021-01-07 22:04 UTC, iche033 commented on src/systems/user_commands/UserCommands.cc
> +      if (lightMsg.type() == msgs::Light::DIRECTIONAL)
nit: `else if`

2021-01-14 01:05 UTC, iche033 reviewed
Looks like the `UserCommndsTest.Create` integration test is failing in the latest build:
https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/5097/testReport/junit/(root)/UserCommandsTest/Create/

2021-01-14 07:41 UTC, ahcorde commented
@iche033 I fixed the test https://github.com/ignitionrobotics/ign-gazebo/pull/513/commits/2d20881652e3b4df2bf1f81144db2c9121f9d394

But I'm curious why is not possible to add more than one light. The SDF format allows to have more than one light as a top-level element. Do you know why this rectriction is here ?

https://github.com/ignitionrobotics/ign-gazebo/blob/66536bb27b1e2a7c57730ce1aa8d49c7777f2b37/src/systems/user_commands/UserCommands.cc#L528-L548

2021-01-14 20:46 UTC, iche033 reviewed
> But I'm curious why is not possible to add more than one light.
 I recall @brawner and @azeey mentioning that we are now limiting the sdf Root to have only contain 1 model/actor/light: https://github.com/osrf/sdformat/pull/444


I also noticed one issue with the light sdf string. Adding quotes around the sdf version number seems to have removed one sdf parsing error msg and increased the entity count in the test.

2021-01-14 21:06 UTC, brawner commented
>> But I'm curious why is not possible to add more than one light.

> I recall @brawner and @azeey mentioning that we are now limiting the sdf Root to have only contain 1 model/actor/light: osrf/sdformat#444

Just to summarize some of the thinking...

Worlds can continue to contain more than 1 of all those items, this just affects `sdf::Root`. The motivation is that including an sdf file using the `<include>` tag leads to ambiguity for the elements in the `<include>` that override elements in the included sdf. For example, which name would the `name` element in the `<include>` tag override if there were more than one model, light or actor in the included file? 

In many places in the code base it was already assumed there was only one model/light/actor element in an sdf root element or included file. For now, we've deprecated that functionality with warnings and in the future it will become a hard error.

2021-01-14 23:20 UTC, iche033 commented
I think we can now revert the change 2d20881652e3b4df2bf1f81144db2c9121f9d394 for the test now the light is being spawned after. This would fix the latest [failing test](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/5116/testReport/)

2021-01-14 23:27 UTC, iche033 commented
> I think we can now revert the change 2d20881 for the test now the light is being spawned after. This would fix the latest failing test

I just did this in de02da50d751fb0c435156ac39a9ccc009c93c16. Let me know if that's not correct. Approving if builds turn green

2021-01-15 06:55 UTC, ahcorde commented
@iche033 CI is green, there are some flaky tests in the buildfarm

2021-01-16 00:45 UTC, iche033 approved these changes

2021-01-16 02:22 UTC, chapulina requested changes
I have some suggestions on #569 on how to address my comments below.

2021-01-16 02:22 UTC, chapulina commented on src/systems/user_commands/UserCommands.cc
> +      sdf::Light sdfLight = convert<sdf::Light>(lightMsg);
Hum, I think this conversion doesn't make sense if we can't use `sdfLight` directly. We could construct the string below using the fields from the message, there's no need to convert to SDF first.

I now realize that there's no way to add a light to `sdf::Root` without converting it to string, and there's no way to get a  string if a light didn't come from an element (https://github.com/osrf/sdformat/issues/468) :confused:

2021-01-20 01:51 UTC, chapulina approved these changes

2021-01-20 01:52 UTC, merged