Added renderOrder to convert functions
ignitionrobotics/ign-gazebo pull request #514
Opened 2020-12-23 15:35 UTC by ahcorde

This PR is part of the effort to avoid z-fighting between coplanar meshes. 

Related with https://github.com/ignitionrobotics/ign-rendering/pull/188

Signed-off-by: ahcorde <ahcorde@gmail.com>

2020-12-23 18:10 UTC, chapulina requested changes

2020-12-23 18:10 UTC, chapulina commented on src/Conversions.cc
> +  out.set_render_order(_in.RenderOrder());
This needs to target `main`, because the `ign-rendering` PR breaks ABI.

2020-12-23 21:19 UTC, ahcorde commented
Retargeted to `main`

2020-12-28 23:23 UTC, chapulina commented
This is blocked by upgrading `ign-gazebo5` to use `ign-msgs7`: https://github.com/ignition-tooling/release-tools/issues/362

2021-01-05 01:43 UTC, chapulina reviewed
Works for me. Mind setting and checking the render order on some tests in `Conversions_TEST`?

2021-01-05 22:28 UTC, chapulina approved these changes
Approved, but it can't be merged until the upgrade to `ign-msgs7` is complete.

2021-01-07 21:35 UTC, iche033 approved these changes

2021-01-13 00:37 UTC, chapulina commented
The `ign-msgs7` upgrade is in, but now we need an SDF10 release: https://github.com/osrf/sdformat/pull/461

2021-01-25 16:59 UTC, chapulina requested changes

2021-01-25 16:59 UTC, chapulina commented on src/Conversions_TEST.cc
> +  EXPECT_DOUBLE_EQ(2.5, pbrMsg.render_order());
This is failing to compile

```suggestion
  EXPECT_DOUBLE_EQ(2.5, materialMsg.render_order());
```

2021-01-25 20:49 UTC, chapulina approved these changes
LGTM, just needs the homebrew bottle to be finished to fix CI: https://github.com/osrf/homebrew-simulation/pull/1307

2021-01-26 09:40 UTC, ahcorde commented
@osrf-jenkins retest this please

2021-01-26 15:38 UTC, ahcorde commented
This failing test is unrelated ServerRepeat/SceneBroadcasterTest.State to this PR. Merging

2021-01-26 15:38 UTC, merged