GPS sensor in Gazebo
ignitionrobotics/ign-gazebo pull request #519
Opened 2020-12-30 08:57 UTC by Dotrar

Related issue:
https://github.com/ignitionrobotics/ign-sensors/issues/23
My pull requests: (This PR would depend on the following: )
https://github.com/ignitionrobotics/ign-sensors/pull/72
(which then depends on)
https://github.com/osrf/sdformat/pull/453

Use the ign-sensor::Gps in the gazebo sim by creating a Gps-system 

This was by far the hardest one to get going, not least due to the "binary/source" issue as mentioned by https://github.com/ignitionrobotics/ign-tools/issues/8 

As mentioned on the sdformat issue, I've only made two simple noise systems that get applied unilaterally to each of the components.. If this doesn't suite I could change it.

I'm also really hoping that the use of `sphericalCoords.PositionTransform()` was correct because I wasn't quite sure on how it's meant to be used; or what a better way to use it _( ie: should the GPS store it's data in a SphericalCoords Type? )_

Some notes:
* I was thinking of putting in a "reference lat/lon" into the sdformat, so that one could specify where the gps starts out in the world file. but I couldn't see that on gazebo classic and I wasn't too sure how the gazebo classic gps function actually worked.

2020-12-30 18:01 UTC, ahcorde requested changes

2020-12-30 18:01 UTC, ahcorde commented on test/integration/gps_system.cc
> + * Copyright (C) 2019 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2020 Open Source Robotics Foundation
```

2020-12-30 18:01 UTC, ahcorde commented on test/integration/gps_system.cc
> +  */
Remove these lines

2021-12-14 00:40 UTC, chapulina commented
Thank you again for all the work, @Dotrar . Since the fork has been deleted, I opened a new PR in #1248.

2021-12-14 00:40 UTC, closed without merging