Add odometry publisher system
ignitionrobotics/ign-gazebo pull request #547
Opened 2021-01-12 02:09 UTC by mrushyendra

Adds a new system that publishes odometry messages for an entity, in a manner similar to what the `ros_planar_move` plugin for Gazebo does. It assumes the robot is on a flat plane and publishes 2D position and velocity data.

There may be other requirements for such a system that I might have missed out on adding, so I can make any changes or additions if necessary.

Closes #465

2021-01-12 10:04 UTC, ahcorde requested changes

2021-01-12 10:04 UTC, ahcorde commented on src/systems/odometry_publisher/OdometryPublisher.cc
> +    "/odometry"};
```suggestion
  std::string odomTopic{transport::TopicUtils::AsValidTopic("/model/" + this->dataPtr->model.Name(_ecm) +
    "/odometry")};
  if (odomTopic.empty())
  {
    ignerr << "Failed to generate odom topic ["
           << this->dataPtr->model.Name(_ecm) << "]" << std::endl;
    return;
  }
```

2021-01-12 10:04 UTC, ahcorde commented on src/systems/odometry_publisher/OdometryPublisher.hh
> + * Copyright (C) 2020 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2021 Open Source Robotics Foundation
```

2021-01-13 06:59 UTC, mrushyendra commented on src/systems/odometry_publisher/OdometryPublisher.cc
> + * Copyright (C) 2020 Open Source Robotics Foundation
Ah yes, of course...

2021-01-13 16:42 UTC, ahcorde requested changes
Can you add some tests ? have a look [here](https://github.com/ignitionrobotics/ign-gazebo/tree/ign-gazebo4/test/integration)

2021-03-15 14:36 UTC, ahcorde requested changes
LGTM, but do you mind to solve the conflics ?

2021-04-06 11:17 UTC, ahcorde commented
friendly ping @mrushyendra

2021-04-08 07:16 UTC, ahcorde commented
@chapulina do you mind to have a quick look here?

2021-04-20 10:32 UTC, ahcorde approved these changes

2021-04-21 07:46 UTC, merged