Bump edifice sdformat11 and ign-physics4
ignitionrobotics/ign-gazebo pull request #549
Opened 2021-01-12 21:54 UTC by chapulina

Addresses https://github.com/ignition-tooling/release-tools/issues/360

2021-01-13 23:20 UTC, j-rivero requested changes

2021-01-13 23:20 UTC, j-rivero commented on CMakeLists.txt
> +ign_find_package(ignition-physics4 VERSION 3.1
```suggestion
ign_find_package(ignition-physics4
```

2021-01-14 03:03 UTC, chapulina commented
Trying a build with https://github.com/ignition-tooling/release-tools/pull/375 to see if all tests pass:

[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-pr_any-ubuntu_auto-amd64&build=5101)](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/5101/)

2021-01-14 17:35 UTC, nkoenig approved these changes

2021-01-19 16:26 UTC, j-rivero approved these changes

2021-01-19 16:26 UTC, merged