Deprecate some gazebo::gui events in favor of ign-gui events
ignitionrobotics/ign-gazebo pull request #595
Opened 2021-01-29 01:23 UTC by chapulina

Builds on top of #591 

---

Deprecate events that have been ported to Ignition GUI.

* Deprecate warnings on v5, remove on v6
* Emitting side emits both old and new events on v5. This should allow plugins using these events to keep working, with warnings.
* Receiving side only processes new events. So if any user plugin is emitting the old events expecting our plugins to react, that won't work anymore. I don't think this is likely though.

2021-02-03 20:44 UTC, caguero approved these changes

2021-02-03 20:45 UTC, caguero requested changes
CI isn't happy. There's a style error.

2021-02-03 21:11 UTC, chapulina commented
> There's a style error.

Fixed in f95d3b3

2021-02-09 07:54 UTC, ahcorde approved these changes

2021-02-09 17:55 UTC, merged