Respect spotlight direction
ignitionrobotics/ign-gazebo pull request #717
Opened 2021-03-28 19:29 UTC by peci1

# 🦟 Bug fix

## Summary
According to SDF and ign-rendering, spot lights have a direction parameter. However, this parameter was ignored when setting the light in the scene. This PR fixes it.

Of course, this might break some scenes which were set up with the direction ignored. However, I still feel that the change is worth it (but I'd suggest the SubT team to thoroughly check if some worlds aren't affected :) ). If merging in Dome is not possible, merge to Edifice, please.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ x All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-03-28 19:34 UTC, peci1 commented
Here's a picture of the current behavior. The link the light is attached to is on the robot's left side with X axis pointing towards the box. I tried many values of the `<direction>` tag, but it always looks the same. If you think it through and connect with the fact that the default value for `<direction>` is `0 0 -1`, this is exactly it. The light is always shining downwards.

Rotating the link itself rotates the light correctly.

![2021-03-28T21:30:52 869741306](https://user-images.githubusercontent.com/182533/112765314-f20ede00-900c-11eb-9c17-7cbfec0abe3b.png)

2021-03-29 06:25 UTC, ahcorde approved these changes

2021-03-29 16:18 UTC, chapulina requested changes
> If merging in Dome is not possible, merge to Edifice, please.

Yeah fixing this bug in Dome could break current users, targeting Edifice feels safer. Would you be able to retarget the PR to `main`? We can get it in before the stable release as a critical bug fix. We should also add a note to the migration guide. Thanks!

2021-03-29 16:24 UTC, peci1 commented
Okay, replaced by #718. I'm not sure if the light visuals do not need some adjustment too, but that can be fixed anytime later without breaking anything.

2021-03-29 16:24 UTC, closed without merging