Multi-LRAUV Swimming Race Example
ignitionrobotics/ign-gazebo pull request #841
Opened 2021-05-29 00:15 UTC by mabelzhang

Signed-off-by: Mabel Zhang <mabel@openrobotics.org>

# 🎉 New feature

## Summary

An example world and controller for a multi-LRAUV swimming race in an underwater environment. Demonstrates how to control the basic set of plugins using a random controller.

Race results vary in every run. Don't take it personally if your favorite LRAUV doesn't win. (Disclosure: they are all the same! Except for their names -- uh oh, shouldn't have said that.)

## Remarks

@arjo129, two things I noticed:
1. `ThrusterPlugin` takes a negative value for going forward. Is that the convention?
   I noticed in the LRAUV model.sdf that the `propeller_joint` is set to negative effort and velocity:
   ```
          <effort>-1</effort>
          <velocity>-1</velocity>
   ```
   Is the actual robot propeller just designed to go forward when rotated in that direction?

2. The robots are going a lot faster here than in our downstream version. All the parameters are the same, and the command values are in the same bounds (other than the thrust being (-lim, 0) as opposed to (0, +lim). Is something different here (did hydrodynamics get faster)?

## Test it

Terminal 1:
```
cd examples/worlds/
ign gazebo -r multi_lrauv_race.sdf
```

Terminal 2:
```
cd examples/standalone/multi_lrauv_race
mkdir build && cd build
cmake ..
make
./multi_lrauv_race
```

You should see something like this:

https://user-images.githubusercontent.com/7608908/120051799-23e1f800-bff0-11eb-894f-295abb4589e7.mp4

## Checklist
- [x] Signed all commits for DCO
- [ ] ~~Added tests~~
- [x] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-05-31 06:48 UTC, arjo129 requested changes
It works for me. If you're curious: Daphne won :trophy:

I've left a comment as to why we seem to be moving so quickly in the review. It has to do with units. Once that is adressed the environment looks good to me.

As for the thrust taking a negative plugin, this is not due to any convention.  To be fair, there are both clockwise and counterclockwise thrusters out there in the wild. As for the effort and velocity being negative, I'm not too sure why they are negative and if this has any impact on the thruster direction at all as the thruster plugin does not read those values.

2021-06-07 18:33 UTC, mabelzhang commented on examples/standalone/multi_lrauv_race/multi_lrauv_race.cc
> +double random_thrust_within_limits(double min=-31.4, double max=31.4)
Cool, thanks! It looks slower now. 585f31e

2021-06-07 18:50 UTC, mabelzhang commented
> As for the effort and velocity being negative, I'm not too sure why they are negative and if this has any impact on the thruster direction at all as the thruster plugin does not read those values.

I should have checked the specs. -1 is actually the default value, to indicate no max is to be enforced. The tags are for max effort and limit. http://sdformat.org/spec?ver=1.8&elem=joint#limit_effort
So no questions there anymore.

> As for the thrust taking a negative plugin, this is not due to any convention. To be fair, there are both clockwise and counterclockwise thrusters out there in the wild.

I wonder if it could be because the current Tethys model has x pointing to the stern. Maybe after we flip it to have x pointing to the bow in some weeks, it'll go forward with positive thrust.

I'm mainly coming from the rationale that if the user does the most vanilla thing with their joint axes and follow the convention (x forward), then when they try out the Thruster plugin, it should do the most intuitive thing, which to me is positive going forward. In this case, I think the model we're using is not following conventions, so that's a problem with the model, not the plugin. Let's see in a few weeks if this is confirmed!

2021-06-10 01:41 UTC, arjo129 approved these changes
This works as described for me. This time both Daphne and Triton were tied :trophy: .

2021-06-10 01:43 UTC, mabelzhang commented
Cool! Daphne wins more for you too huh, she won the most for me in the beginning but later spread out better, I think. I'm gonna rerun CI because this looks too red even for an example that shouldn't affect the tests...

2021-06-10 01:45 UTC, mabelzhang commented
@osrf-jenkins run tests

2021-06-12 00:58 UTC, mabelzhang commented
Double-checked that the failed Ubuntu tests are flaky. Actually all OSes' CI have flaky tests and none are required apparently :sweat_smile:
Merging.

2021-06-12 02:52 UTC, merged