Make Gazebo aware of SetCameraPassCountPerGpuFlush
ignitionrobotics/ign-gazebo pull request #921
Opened 2021-07-17 23:25 UTC by darksylinc

# 🎉 New feature

See ignitionrobotics/ign-rendering/issues/323

## Summary

ign-rendering has a new feature aimed to improve performance but also fixes a few bugs related to particle simulations; which is controlled via `Scene::SetCameraPassCountPerGpuFlush`.

A value of 0 will use the legacy mode (i.e. previous behavior) to ease porting from older version.
A value > 0 controls performance vs RAM tradeoff (note that it is an upper limit; a very high value doesn't immediately waste RAM. See `Scene::SetCameraPassCountPerGpuFlush` documentation for details)

This PR depends on https://github.com/ignitionrobotics/ign-rendering/pull/353 **otherwise it will not compile**.

## Test it

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-07-19 15:42 UTC, ahcorde requested changes
style

2021-07-19 15:42 UTC, ahcorde commented on src/gui/plugins/scene3d/Scene3D.cc
> +  scene->SetCameraPassCountPerGpuFlush( 6u );
```suggestion
  scene->SetCameraPassCountPerGpuFlush(6u);
```

2021-07-19 15:42 UTC, ahcorde commented on src/systems/sensors/Sensors.cc
> +      this->scene->SetCameraPassCountPerGpuFlush( 6u );
```suggestion
      this->scene->SetCameraPassCountPerGpuFlush(6u);
```

2021-07-21 16:19 UTC, iche033 commented
@osrf-jenkins run tests please

2021-07-22 07:15 UTC, ahcorde approved these changes

2021-07-22 16:14 UTC, iche033 approved these changes

2021-07-22 16:14 UTC, merged