Extend odom publisher to allow 3D
ignitionrobotics/ign-gazebo pull request #941
Opened 2021-07-29 18:21 UTC by blakermchale

# 🎉 New feature

Closes #934

## Summary
This adds in a new tag `<dimensions>` to the odometry publisher plugin that accepts either 2 or 3 (defaults to 2). When the value is 3 it assumes a 3D assumption instead of planar. This is useful for people who want to know the z location and angular rates. In my use case, I was using the multicopter plugin with the X3 model.

## Test it
This feature can be tested by running the `INTEGRATION_odometry_publisher` test or adding the tag to the plugin in an SDF file. I tested this manually and echoed the odometry topic while commanding the multicopter with velocities.

## Checklist
- [X] Signed all commits for DCO
- [X] Added tests
- [ ] Added example and/or tutorial
- [X] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [X] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-08-02 12:14 UTC, vatanaksoytezer commented
I've tested this and seem to work pretty well, thanks @blakermchale

2021-08-09 10:43 UTC, ahcorde requested changes
There are some Windows warnings. Include this change in this line https://github.com/ignitionrobotics/ign-gazebo/blob/be6c1a36142bbc0c50a2d39d397e8dd38317d83a/src/systems/odometry_publisher/OdometryPublisher.cc#L20

```
#ifdef _MSC_VER
#pragma warning(push, 0)
#endif
#include <ignition/msgs/odometry.pb.h>
#ifdef _MSC_VER
#pragma warning(pop)
#endif
```

2021-08-09 10:43 UTC, ahcorde commented on src/systems/odometry_publisher/OdometryPublisher.cc
> +#include <tuple>
Alphabetize

2021-08-09 10:43 UTC, ahcorde commented on test/integration/odometry_publisher.cc
> +      "/test/worlds/odometry_publisher_3d.sdf",
`ignition::common::JoinPath()`

2021-08-09 10:43 UTC, ahcorde commented on test/integration/odometry_publisher.cc
> +            gazebo::EntityComponentManager &_ecm)
```suggestion
            gazebo::EntityComponentManager &/*_ecm*/)
```

2021-08-16 01:19 UTC, blakermchale commented
This isn't related to the PR directly, but are there any recommendations on how to perform DCO signoffs if I missed them? I used the recommended commands and did some re-basing, however, it always ends up having conflicts and requiring me to confirm changes that I never made.

I'm fairly new to contributing to open source since I'm a college student, so any tips would be greatly appreciated.

2021-09-09 21:49 UTC, chapulina reviewed
Thanks for the PR, LGTM! There are just some small details to be fixed.

> are there any recommendations on how to perform DCO signoffs if I missed them? 

Be sure to sign every single commit when rebasing. You may want to squash all commits so you only need to sign one, if that makes it easier.

2021-09-09 21:49 UTC, chapulina commented on src/systems/odometry_publisher/OdometryPublisher.cc
> +    ignwarn << "OdometryPublisher system plugin missing <dimensions>, "
Not setting dimensions is a valid use case, so we don't need to bother users with a warning. I think `igndbg` should be enough here.

2021-11-08 23:18 UTC, chapulina commented
@blakermchale , are you still interested in getting this PR in? Let us know how we can help. It would be great if you could at least sign your commits. Thanks!

2021-11-09 01:33 UTC, vatanaksoytezer commented
@chapulina @blakermchale I'll also be more than happy to help close out this PR as currently I am using this feature and building Ignition on top of this PR.

2021-11-09 01:54 UTC, chapulina commented
Thanks, @vatanaksoytezer , that would be great! You may need to open a new PR. We can close this one when you do.

2021-11-09 03:46 UTC, blakermchale commented
Thanks for pinging me on this @chapulina! I'm going to close this PR and just open a new one with the changes I made signed off.

2021-11-09 03:46 UTC, closed without merging